STYLE_JSON = {
    "2d_Cartoon": {
        "visual_style": "2D animation style, flat perspective with clean outlines, bold line art, and simplified forms. Characters and objects are illustrated with consistent cel shading or flat coloring, no depth simulation. Movements are smooth but intentionally stylized, frame-by-frame animation with strong silhouettes. Backgrounds kept simple or hand-drawn, emphasizing shapes and colors rather than realism. Aesthetic inspired by traditional 2D animated films and TV series. NOT 3D, NOT CGI, NOT photorealistic, NOT live-action. Aspect ratio 16:9 full frame, no borders, no black bars."
    },
    "3d_Cartoon": {
        "visual_style": "3D cartoon animation style, stylized proportions, exaggerated features, smooth simplified textures, vibrant saturated colors, soft rounded forms, non-photorealistic rendering, toon shading, playful character design. Style reference: Pixar/DreamWorks. NOT realistic, NOT photorealistic, warm morning sunlight, soft shadows, non-photorealistic, en-US dialogue in brackets, no text overlays."
    },
    "3D_CGI_Realistic": {
        "visual_style": "3D CGI realistic style, hyper-detailed character models with lifelike proportions and anatomically correct features. Physically-based rendering (PBR) with accurate material response: realistic skin, cloth, metal, wood, and organic surfaces. High-resolution textures, subsurface scattering, ray-traced reflections, global illumination, and cinematic depth of field. Natural lighting setups (sunlight, studio, volumetric light) with accurate shadows. Realistic hair and cloth physics for authentic motion. Style reference: Pixar realism, DreamWorks, Disney modern CGI films. NOT live-action, NOT 2D, NOT cartoon, NOT stylized, NOT hand-drawn. Aspect ratio 16:9 full frame, no top or bottom borders, no black bars."
    },
    "3d_Pixar": {
        "visual_style": "High-quality 3D animated film style inspired by modern Western animated cinema, soft rounded and friendly character designs, slightly exaggerated facial expressions for emotional clarity, clean and smooth surfaces, richly detailed yet whimsical environments, cinematic lighting with warm golden-hour tones, soft shadows and gentle depth of field, non-photorealistic, stylized realism, emotionally expressive, heartwarming tone, professional studio-quality animation, no text overlays."
    },
    "Anime_Japan": {
        "visual_style": "Japanese anime style, 2D hand-drawn look with clean line art, vibrant cel shading, and expressive character design. Large detailed eyes, stylized hair with dynamic flow, and exaggerated emotional expressions. Smooth frame-by-frame motion inspired by classic and modern anime studios. Backgrounds richly painted with anime aesthetics: soft gradients, dramatic skies, detailed cityscapes, or natural landscapes. Cinematic composition, atmospheric lighting, and artistic color grading. Style reference: Makoto Shinkai films (Your Name, Weathering With You), Studio Ghibli. NOT 3D, NOT CGI, NOT photorealistic, NOT live-action. Aspect ratio 16:9 full frame, no borders, no black bars."
    },
    "CCTV_Found_Footage": {
        "visual_style": "CCTV / Found footage style, filmed as if captured by surveillance cameras or handheld amateur devices. Realistic human appearance with unpolished, raw visuals. Low resolution, slight pixelation, compression artifacts, time stamps, and static noise. Camera angles are fixed (for CCTV) or shaky and unstable (for handheld). Lighting is natural or harsh from existing sources like streetlights, indoor fluorescents, or headlights. Atmosphere is tense, gritty, and authentic, evoking security feeds or discovered footage. Style reference: horror found footage films and real surveillance recordings. Aspect ratio 16:9 full frame, no top or bottom borders, no black bars. NOT CGI, NOT animated, NOT cartoon, NOT stylized, NOT 3D, NOT render."
    },
    "Documentary_style": {
        "visual_style": "Documentary style, filmed with real people and authentic locations. Naturalistic appearance with realistic skin tones, clothing, and environments. Captured using handheld or shoulder-mounted cameras, giving a raw and unscripted feel. Lighting is natural and available (daylight, indoor lamps, streetlights), without dramatic staging. Sound and visuals emphasize realism over polish. Movements, gestures, and expressions are genuine and unscripted, as if observing real life. Visuals may include slight camera shake, zooms, or imperfections that reinforce authenticity. Style reference: National Geographic, BBC Earth, Netflix documentaries. Aspect ratio 16:9 full frame, no top or bottom borders, no black bars. NOT CGI, NOT animated, NOT cartoon, NOT stylized, NOT 3D, NOT render."
    },
    "Epic_survival_cinematic": {
        "visual_style": "Live-action prehistoric survival with a naturalistic docu-drama tone and epic vistas. Lighting: sun/overcast, fire/ember glow, moonlight; smoke, dust, and fog used as organic diffusion—no modern fixtures. Earthy palette (ochre, umber, charcoal, moss green; cool dawn/blue hour). Weathered skin with dirt, sweat, scars; cracked hands; tangled hair; ritual pigments (charcoal/ochre). Authentic props (bone/stone/wood tools, sinew lashings), hand-stitched hides/fibers; no metal or plastic. Camera: real-lens behavior 18–85 mm, low near-ground angles, shoulder/handheld with gentle drift; slow push-ins; occasional crane/aerial for migrations; shallow DOF for close work, deep focus for landscapes; 24 fps, 180° shutter, subtle film grain. Sound: rich ambience (wind, grass, insects, water, distant animals, fire crackle); foley of leather/stone/bone; minimal percussive score (skin drums, bone flutes). Grading: restrained contrast, natural skin tones, patina of age. (Negative Prompt: black bars, top bars, bottom bars, letterbox, pillarbox, cinema bars, mattes, padding, blur background, solid-color borders, vignette edges, frame border, watermark, captions, subtitles, UI overlay). Aspect ratio (16:9 or 9:16) EDGE-TO-EDGE — ABSOLUTELY NO borders/letterboxing/pillarboxing/mattes. Scale = COVER/FILL. If framing mismatches (16:9 or 9:16), CENTER-CROP to fit; DO NOT pad. Deliver full-frame only; safe area 100%; no text/watermarks. NOT CGI, NOT animated, NOT cartoon, NOT stylized, NOT 3D, NOT render."
    },
    "Experimental_Art_film": {
        "visual_style": "Experimental art film style, abstract and surreal imagery with unconventional framing, unusual camera angles, and non-linear visual storytelling. Real actors or real objects are filmed but presented in dreamlike, fragmented, or symbolic ways. Lighting can be stark, colored, or high-contrast, often creating painterly or theatrical moods. Emphasis on atmosphere, emotion, and metaphor rather than narrative clarity. May include slow motion, extreme close-ups, or distorted perspectives. Style reference: arthouse cinema and avant-garde short films. Aspect ratio 16:9 full frame, no top or bottom borders, no black bars. NOT CGI, NOT animated, NOT cartoon, NOT stylized, NOT 3D, NOT render."
    },
    "Live_action_cinematic": {
        "visual_style": "Live-action cinematic style, filmed with real actors and authentic environments. Natural human appearance with realistic skin tones, hair, and clothing. Captured using professional cinema cameras with high resolution, shallow depth of field, and cinematic framing. Lighting based on real-world conditions: golden hour sunlight, soft indoor ambient, or dramatic studio setups. Realistic lens effects: lens flares, natural bokeh, slight film grain. Movements and expressions are genuine human performances, exactly like feature films. Style reference: mainstream Hollywood cinema and high-end commercials. High resolution, ultra sharp detail, cinematic color grading, balanced natural tones. Aspect ratio 16:9 EDGE-TO-EDGE — ABSOLUTELY NO borders, NO letterboxing/pillarboxing, NO mattes. Always scale = COVER (FILL FRAME). If source framing mismatches 16:9, CENTER-CROP to fit; DO NOT pad. Deliver full-frame images only; safe area 100%; no text overlays or watermarks. NOT CGI, NOT animated, NOT cartoon, NOT stylized, NOT 3D, NOT render."
    },
    "Music_Video_Aesthetic": {
        "visual_style": "Music video aesthetic, filmed with real performers and stylish environments. High-contrast lighting with colorful stage effects, neon glows, lens flares, and dramatic spotlighting. Cinematic camera moves with dynamic angles, smooth tracking shots, and slow motion to emphasize rhythm. Emphasis on fashion, makeup, choreography, and performance energy. Color grading is vibrant and stylized, often with saturated tones or moody cinematic palettes depending on the mood of the song. Atmosphere is glossy, trendy, and high-production like MTV or K-pop videos. Aspect ratio 16:9 full frame, no top or bottom borders, no black bars. NOT CGI, NOT animated, NOT cartoon, NOT stylized 3D, NOT render."
    },
    "Noir_Black_and_White": {
        "visual_style": "Film noir black and white style, filmed with real actors and realistic settings. High-contrast monochrome imagery with deep shadows and sharp highlights. Strong use of chiaroscuro lighting, Venetian blinds, smoke, and rain-soaked streets to create dramatic tension. Characters appear in trench coats, fedoras, or period-accurate attire, with expressive gestures and subtle emotional nuance. Cinematic depth of field, moody atmosphere, and classic noir framing with tilted angles and shadow play. Style reference: 1940s–1950s noir cinema. Aspect ratio 16:9 full frame, no top or bottom borders, no black bars. NOT CGI, NOT animated, NOT cartoon, NOT stylized, NOT 3D, NOT render."
    },
    "Pixel_Art_8bit": {
        "visual_style": "Pixel art retro game style, low-resolution 8-bit or 16-bit graphics with blocky pixels clearly visible. Characters and objects simplified into chunky pixel forms with limited color palettes, sharp outlines, and nostalgic arcade aesthetics. Animation choppy but stylized, mimicking old NES/SNES era games. Backgrounds tiled or grid-based with repeating patterns. Emphasize retro charm, minimal shading, and nostalgic game feel. Style reference: classic Nintendo and Sega pixel games. NOT 3D, NOT realistic, NOT cinematic, NOT photorealistic. Aspect ratio 16:9 full frame, no top or bottom borders, no black bars."
    },
    "POV_First_person": {
        "visual_style": "POV (first-person perspective) style, filmed as if seen directly through the eyes of the main character. Realistic human interactions, hands and body occasionally visible in frame to reinforce immersion. Natural environments and authentic lighting conditions (daylight, indoor ambient, streetlights at night) captured with head-mounted or handheld cameras. Movements may include natural shakes, tilts, and quick turns, mimicking real vision. Sound design emphasizes proximity and realism, enhancing the immersive feel. Atmosphere gives the viewer the sense of being physically present in the scene. Style reference: immersive GoPro footage, VR first-person films. Aspect ratio 16:9 full frame, no top or bottom borders, no black bars. NOT CGI, NOT animated, NOT cartoon, NOT stylized, NOT 3D, NOT render."
    },
    "Realistic": {
        "visual_style": "Live-action cinematic style, filmed with real actors and realistic environments. Natural human appearance with authentic skin tones, hair, and clothing. Shot with professional cameras, cinematic depth of field, natural lighting (sunlight, soft shadows, indoor ambient light), and realistic lens effects. Movements, gestures, and expressions appear exactly like real human performances. Style reference: mainstream feature films and high-end commercials. High resolution, ultra sharp detail, cinematic color grading, balanced natural colors. (Negative Prompt: black bars, top bars, bottom bars, letterbox, pillarbox, cinema bars, mattes, padding, blur background, solid-color borders, vignette edges, frame border, watermark, captions, subtitles, UI overlay). Aspect ratio (16:9 or 9:16) EDGE-TO-EDGE — ABSOLUTELY NO borders/letterboxing/pillarboxing/mattes. Scale = COVER/FILL. If framing mismatches (16:9 or 9:16), CENTER-CROP to fit; DO NOT pad. Deliver full-frame only; safe area 100%; no text/watermarks. NOT CGI, NOT animated, NOT cartoon, NOT stylized, NOT 3D, NOT render."
    },
    "Realistic_CGI": {
        "visual_style": "Photorealistic CGI rendering, hyperrealistic human features, lifelike skin textures with subsurface scattering, realistic hair physics, accurate fabric simulation, physically-based rendering (PBR), volumetric lighting, ray-traced reflections, cinematic depth of field. Style reference: Avatar, The Jungle Book (2016). NOT cartoon, NOT stylized, soft afternoon sun, long shadows, photorealistic rendering, en-US dialogue in brackets, no text overlays."
    },
    "Reallistic_CGI": {
        "visual_style": "Photorealistic CGI rendering, hyperrealistic human features, lifelike skin textures with subsurface scattering, realistic hair physics, accurate fabric simulation, physically-based rendering (PBR), volumetric lighting, ray-traced reflections, cinematic depth of field. Style reference: Avatar, The Jungle Book (2016). NOT cartoon, NOT stylized, soft afternoon sun, long shadows, photorealistic rendering, en-US dialogue in brackets, no text overlays."
    },
    "Theatrical_Stage_performance": {
        "visual_style": "Theatrical stage performance style, filmed with real performers on stage in a controlled environment. Strong spotlighting, dramatic shadows, and visible stage elements such as curtains, props, and set design. Actors wear detailed costumes and makeup, performing expressive gestures and exaggerated body language suited for live theater. Camera angles capture both wide shots of the stage and close-ups of performers, highlighting emotion and drama. Color grading is natural with theatrical lighting hues (warm tungsten, deep blues, intense reds). Atmosphere resembles live drama, opera, or musical stage shows. Aspect ratio 16:9 full frame, no top or bottom borders, no black bars. NOT CGI, NOT animated, NOT cartoon, NOT stylized, NOT 3D, NOT render."
    },
    "Vintage_Rentro": {
        "visual_style": "Vintage retro film look, filmed with real actors and authentic environments. Warm faded color grading, slight film grain, dust, scratches, and subtle vignette to mimic old film reels. Natural skin tones with a nostalgic hue, softer focus, and reduced contrast. Lighting styled after classic cinema: tungsten indoor lights, warm sunlight, or neon retro glow. Camera movement may include zooms, pans, or slight jitter typical of analog film. Style reference: 70s–90s cinema, old home movies, retro commercials. Aspect ratio 16:9 full frame, no top or bottom borders, no black bars. NOT CGI, NOT animated, NOT cartoon, NOT stylized, NOT 3D, NOT render."
    },
}
